baseURL = "https://tranghoangproject.netlify.app"
languageCode = "en-us"
title = "Trang Hoang project"
theme = "anubis"

[menu]

[[menu.main]]
identifier = "about me"
name = "about me"
url = "/content/post/about_me.md"
weight = 1

[[menu.main]]
identifier = "my project"
name = "my project"
url = "/content/post/my_project.md"
weight = 3

[[menu.main]]
identifier = "article"
name = "article"
url = "/content/post/article.md"
weight = 3


