baseURL = "https://tranghoangproject.netlify.app"
languageCode = "en-us"
title = "Trang Hoang project"
theme = "anubis"

[menu]

[[menu.main]]
identifier = "about me"
name = "about me"
url = "/content/post/Home.md"
weight = 1

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 2

[[menu.main]]
name = "Archive"
identifier = "archive"
url = "/posts/"
weight = 3
