baseURL = "https://tranghoangproject.netlify.app"
languageCode = "en-us"
title = "HOME"
theme = "anubis"

![alt text]("resources/_gen/images/cover_pic.jpg")

[menu]

[[menu.main]]
identifier = "about me"
name = "ABOUT ME"
url = "/content/post/about_me.md"
weight = 1

[[menu.main]]
identifier = "my project"
name = "MY PROJECT"
url = "/content/post/my_project.md"
weight = 2

[[menu.main]]
identifier = "article"
name = "ARTICLE"
url = "/content/post/article.md"
weight = 3


